Ignore rbx failures on Travis
These appear to be due to rbx bugs, not bugs in Sequel (e.g.
<NoMethodError: undefined method `ascii_compatible?' on nil:NilClass.>)