Possgres JDBC adapter - code breaks inside rescue
If bad params are provided to the copy_into command, copier object doesn't get instantiated. This causes an error (NoMethodError Exception: undefined method `cancelCopy' for nil:NilClass) at line: 76.
This masks the original error being raised.