Work around a bug in SQL Server JDBC Driver 3.0.
The metadata for the getColumns result set specifies an incorrect
type for the IS_AUTOINCREMENT column. The column is a string, but the
type is specified as a short. This causes getObject() to throw a
com.microsoft.sqlserver.jdbc.SQLServerException: "The conversion
from char to SMALLINT is unsupported." Using getString() rather
than getObject() for this column avoids the problem.

Reference: http://social.msdn.microsoft.com/Forums/en/sqldataaccess/thread/20df12f3-d1bf-4526-9daa-239a83a8e435