Avoid error when building website
When running www/make_guides.rb with a non-UTF-8 environment
(such as when $LANG is unset), resulted in:

  ArgumentError: invalid byte sequence in US-ASCII (ArgumentError)

We don't need encoding handling here, so switch to binread.